name: conditional steps

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/conditional-steps.yml
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  with-skipped:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "no-op"
  with-skipped--gate:
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: [with-skipped]
    if: |-
      !failure() && !cancelled()
    steps:
      - run: echo "no-op"

  should-run-gate-truthy:
    runs-on: ubuntu-latest
    needs: [with-skipped--gate]
    steps:
      - run: echo "I run"
  
  always-fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  should-run-gate-truthy--explicit:
    runs-on: ubuntu-latest
    needs: [with-skipped--gate]
    if: |-
      !failure() && !cancelled()
      && !contains(needs.*.result, 'failure')
    steps:
      - run: echo "I run"

  no-run-gate-truthy--other-job-failed:
    runs-on: ubuntu-latest
    needs: [with-skipped--gate, always-fail]
    if: |-
      !failure() && !cancelled()
    steps:
      - run: echo "I will not run"
  
  capture-context:
    runs-on: ubuntu-latest
    needs:
      - with-skipped
      - with-skipped--gate
      - should-run-gate-truthy
      - always-fail
      - should-run-gate-truthy--explicit
      - no-run-gate-truthy--other-job-failed
    if: always() && !cancelled()
    env:
      _NEEDS_CONTEXT: "${{ toJSON(needs) }}"
    steps:
      - run: echo "$_NEEDS_CONTEXT"

  with-failure:
    runs-on: ubuntu-latest
    steps:
      - if: failure()
        run: |
          echo "This will never show, as a failure hasn't occurred yet"
          echo "status: ${{ job.status }}"
      - id: fails
        run: |
          echo "status: ${{ job.status }}"
          exit 1
      - run: |
          echo "This should never show"
          echo "status: ${{ job.status }}"

      - if: failure()
        run: |
          echo "This will show when there is a prior failure"
          echo "status: ${{ job.status }}"

      - if: always()
        run: |
          echo "this will always show, no matter what"
          echo "status: ${{ job.status }}"

      - if: ${{ !cancelled() }}
        run: |
          echo "this should show, as docs suggest"
          echo "status: ${{ job.status }}"

      - if: success()
        run: |
          echo "this will never show"
          echo "status: ${{ job.status }}"
