name: conditional jobs

on:
  push:
    branches: [main]
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  never-runs:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "How did we get here...."
          exit 1

  run-with-error:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
     - run: exit 1

  skips-due-to-needs:
    runs-on: ubuntu-latest
    needs: [never-runs]
    steps:
      - run: |
          echo "How did we get here...."
          exit 1

  skips-due-to-needs--success-func-has-bad-docs:
    runs-on: ubuntu-latest
    needs: [never-runs]
    # https://docs.github.com/en/actions/learn-github-actions/expressions#success
    # "Returns true when none of the previous steps have failed or been canceled."
    #
    # Not true, it also returns false when the needed steps have been skipped
    # Note: this is the default if you don't define 'if'
    if: success()
    steps:
      - run: |
          echo "How did we get here...."
          exit 1

  skips-due-to-needs--longform:
    runs-on: ubuntu-latest
    needs: [never-runs]
    # This is as close as we can get to the behaviour of success()
    # Note: there isn't a way for us to say "all items in array are a value"
    if: |
      !(cancelled() || failure())
      && !(
        contains(needs.*.result, 'skipped')
      )
    steps:
      - run: |
          echo "How did we get here...."
          exit 1

  # don't do this, as it breaks cancelling
  always-runs-ignoring-needs--avoid:
    needs: [never-runs]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: |
          echo "Hello, there 👀"

  always-runs-ignoring-needs--permit-failures:
    needs: [never-runs]
    runs-on: ubuntu-latest
    # NOTE: "key: !val" has special meaning in YAML
    if: ${{ !cancelled() }}
    steps:
      - run: |
          echo "Hello, again"

  runs-ignoring-needs:
    needs: [never-runs]
    runs-on: ubuntu-latest
    if: ${{ !(cancelled() || failure()) }}
    steps:
      - run: |
          echo "Hello, successful"

  runs-BECAUSE-needs-were-skipped:
    needs: [never-runs]
    runs-on: ubuntu-latest
    if: |
      !(cancelled() || failure())
      && needs.never-runs.result == 'skipped'
    steps:
      - run: |
          echo "Opposite day!"

  maybe-runs--needs-say-continue:
    needs: [run-with-error]
    runs-on: ubuntu-latest
    steps:
      - run: echo "did we make it"
