name: conditional steps

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/conditional-steps.yml
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  with-skipped:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "no-op"
  depends-on-skipped:
    runs-on: ubuntu-latest
    needs: [with-skipped]
    steps:
      - run: echo "I ran"
  depends-on-skipped--explicit-allow:
    runs-on: ubuntu-latest
    needs: [with-skipped]
    if: |-
      always() && !cancelled()
      && (
        needs.with-skipped.result == 'success'
        || needs.with-skipped.result == 'skipped'
      )
    steps:
      - run: echo "I ran"
  implicit-depends-on-skipped:
    runs-on: ubuntu-latest
    needs: [depends-on-skipped--explicit-allow]
    steps:
      - run: echo "I will not run due to implicit needs"
  
  implicit-depends-on-skipped--explicit-allow:
    runs-on: ubuntu-latest
    needs: [depends-on-skipped--explicit-allow]
    if: |-
      always() && !cancelled()
      && !contains(needs.*.result, 'skipped')
      && !contains(needs.*.result, 'failure')
    steps:
      - run: echo "I will run"

  with-failure:
    runs-on: ubuntu-latest
    steps:
      - if: failure()
        run: |
          echo "This will never show, as a failure hasn't occurred yet"
          echo "status: ${{ job.status }}"
      - id: fails
        run: |
          echo "status: ${{ job.status }}"
          exit 1
      - run: |
          echo "This should never show"
          echo "status: ${{ job.status }}"

      - if: failure()
        run: |
          echo "This will show when there is a prior failure"
          echo "status: ${{ job.status }}"

      - if: always()
        run: |
          echo "this will always show, no matter what"
          echo "status: ${{ job.status }}"

      - if: ${{ !cancelled() }}
        run: |
          echo "this should show, as docs suggest"
          echo "status: ${{ job.status }}"

      - if: success()
        run: |
          echo "this will never show"
          echo "status: ${{ job.status }}"
