name: multiline expressions

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/multiline-expressions.yml
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  # note, all of these have a blank link after the object
  LITERAL_CHOMP_CLIP: |
    ${{
      true
      && 'bar'
    }}
    
  LITERAL_CHOMP_STRIP: |-
    ${{
      true
      && 'bar'
    }}
    
  LITERAL_CHOMP_KEEP: |+
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_CLIP: >
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_STRIP: >-
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_KEEP: >+
    ${{
      true
      && 'bar'
    }}
    
jobs:
  simple:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - id: plain
        name: Plain
        # equiv: false
        if: ${{ false }}
        run: echo "this runs"

      - id: foo
        name: Foo
        # runs because the string "true\n" is truthy
        # equiv: format('{0}\n', true)
        if: |
          ${{
            true
          }}
        run: echo "it runs"

      - id: bar
        name: Bar
        # runs because the string "false\n" is truthy
        # equiv: format('{0}\n', false)
        if: |
          ${{
            false
          }}
        run: echo "it runs"

      - id: zed
        name: Zed
        # runs as '&& true' is added as string ("false\n&& true\n")
        # equiv: format('{0}\n&& true\n', false)
        if: |
          ${{
            false
          }}
          && true
        run: echo "it runs"

      - id: doodar
        name: Doodar
        # the block is still a string
        # equiv: format('true\n&& {0}\n&& true\n', false)
        if: |
          true
          && ${{
            false
          }}
          && true
        run: echo "it runs"

      - id: eggz
        name: Eggz
        # equiv: format('true && {0}\n&& true\n', false)
        if: |
          true && ${{ false }}
          && true
        run: echo "it runs"

      - id: eggzTrimmed
        name: Eggz Trimmed
        # equiv: format('true && {0}\n&& true', false)
        if: |-
          true && ${{ false }}
          && true
        run: echo "it runs"

      - id: fred
        name: Fred
        # equiv: format('true && {0} && true', false)
        if: true && ${{ false }} && true
        run: echo "it runs"

      - id: dave
        name: Dave
        # equiv: format('{0} == true', false)
        if: ${{ false }} == true
        run: echo "it runs"

      - id: jeff
        name: Jeff
        # equiv: true && false && true
        if: |
          true
          
          && false
          
          && true
        run: echo "it runs"
      
      - id: stringyTrue
        name: Stringy True
        if: 'true'
        run: echo "it runs"
      
      - id: stringyFalse
        name: Stringy True
        if: 'false'
        run: echo "it runs"

      - name: CheckPlain
        if: always() && steps.plain.outcome != 'skipped'
        run: |
          echo "Plain ran when it should not have"
          exit 1
      - name: CheckFoo
        if: always() && steps.foo.outcome != 'success'
        run: |
          echo "Foo did not run when it should have"
          exit 1
      - name: CheckBar
        if: always() && steps.bar.outcome != 'skipped'
        run: |
          echo "Bar ran when it should not have"
          exit 1
      - name: CheckZed
        if: always() && steps.zed.outcome != 'skipped'
        run: |
          echo "Zed ran when it should not have"
          exit 1
      - name: CheckDoodar
        if: always() && steps.doodar.outcome != 'skipped'
        run: |
          echo "Doodar ran when it should not have"
          exit 1
      - name: CheckEggz
        if: always() && steps.eggz.outcome != 'skipped'
        run: |
          echo "Eggz ran when it should not have"
          exit 1
      - name: CheckEggzTrimmed
        if: always() && steps.eggzTrimmed.outcome != 'skipped'
        run: |
          echo "Eggz Trimmed ran when it should not have"
          exit 1
      - name: CheckFred
        if: always() && steps.fred.outcome != 'skipped'
        run: |
          echo "Fred ran when it should not have"
          exit 1
      - name: CheckDave
        if: always() && steps.dave.outcome != 'skipped'
        run: |
          echo "Dave ran when it should not have"
          exit 1
      - name: CheckJeff
        if: always() && steps.jeff.outcome != 'skipped'
        run: |
          echo "Jeff ran when it should not have"
          exit 1
      - name: CheckStringyTrue
        if: always() && steps.stringyTrue.outcome != 'success'
        run: |
          echo "stringyTrue did not run when it should have"
          exit 1
      - name: CheckStringyFalse
        if: always() && steps.stringyFalse.outcome != 'skipped'
        run: |
          echo "stringyFalse ran when it should not have"
          exit 1





  main:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "main SHOULD_RUN=${{ matrix.shouldRun }}"
    strategy:
      fail-fast: false
      matrix:
        shouldRun: [1, 0]
    env:
      SHOULD_RUN: ${{ matrix.shouldRun }}
    steps:
      - id: WRAPPED_LITERAL_CHOMP_CLIP
        name: WRAPPED_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LITERAL_CHOMP_STRIP
        name: WRAPPED_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LITERAL_CHOMP_KEEP
        name: WRAPPED_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_CLIP
        name: WRAPPED_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_STRIP
        name: WRAPPED_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_KEEP
        name: WRAPPED_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
      - id: WRAPPED_LEADING_LITERAL_CHOMP_CLIP
        name: WRAPPED_LEADING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_LITERAL_CHOMP_STRIP
        name: WRAPPED_LEADING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_LITERAL_CHOMP_KEEP
        name: WRAPPED_LEADING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_CLIP
        name: WRAPPED_LEADING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_STRIP
        name: WRAPPED_LEADING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_KEEP
        name: WRAPPED_LEADING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_DANGLING_LITERAL_CHOMP_CLIP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_LITERAL_CHOMP_STRIP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_LITERAL_CHOMP_KEEP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_CLIP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_STRIP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_KEEP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_CLIP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_STRIP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_KEEP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_CLIP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_STRIP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_KEEP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: LITERAL_CHOMP_CLIP
        name: LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          always()
          && matrix.shouldRun == 1
          
      - id: LITERAL_CHOMP_STRIP
        name: LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          always()
          && matrix.shouldRun == 1
          
      - id: LITERAL_CHOMP_KEEP
        name: LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_CLIP
        name: FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_STRIP
        name: FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_KEEP
        name: FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          always()
          && matrix.shouldRun == 1
          

      # validation
      - name: fail if any skipped when they should run
        if: |
          always()
          && matrix.shouldRun == 1
          && contains(steps.*.outcome, 'skipped')
        run: exit 1

      - name: fail if any ran while when they should not run
        if: |
          always()
          && matrix.shouldRun == 0
          && (
            contains(steps.*.outcome, 'success')
            || contains(steps.*.outcome, 'failure')
          )
        run: exit 1

      - name: dump results
        if: always()
        env:
          _STEPS_CONTEXT: ${{ toJSON(steps) }}
          _JOB_CONTEXT: ${{ toJSON(job) }}
          _STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          _MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          _STEP_ENV_CONTEXT: ${{ toJSON(env) }}
        run: |
          echo "steps: ${_STEPS_CONTEXT}"
          echo "job: ${_JOB_CONTEXT}"
          echo "strategy: ${_STRATEGY_CONTEXT}"
          echo "matrix: ${_MATRIX_CONTEXT}"
          echo "job env: ${_ENV_CONTEXT}"
          echo "step env: ${_STEP_ENV_CONTEXT}"
