name: multiline expressions

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/multiline-expressions.yml
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  # note, all of these have a blank link after the object
  LITERAL_CHOMP_CLIP: |
    ${{
      true
      && 'bar'
    }}
    
  LITERAL_CHOMP_STRIP: |-
    ${{
      true
      && 'bar'
    }}
    
  LITERAL_CHOMP_KEEP: |+
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_CLIP: >
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_STRIP: >-
    ${{
      true
      && 'bar'
    }}
    
  FOLDED_CHOMP_KEEP: >+
    ${{
      true
      && 'bar'
    }}
    
jobs:
  simple:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      forced_string_false: "${{ 'fal' }}${{ 'se' }}"
      literal_string_false: 'false'
      actual_false: false
    steps:
      - name: '{{ false }}'
        # equiv: false
        if: ${{ false }}
        run: echo "this runs"

      - name: '{{ true }}\n'
        # runs because the string "true\n" is truthy
        # equiv: format('{0}\n', true)
        if: |
          ${{
            true
          }}
        run: echo "it runs"

      - name: '{{ false }}\n'
        # runs because the string "false\n" is truthy
        # equiv: format('{0}\n', false)
        if: |
          ${{
            false
          }}
        run: echo "it runs"

      - name: '{{ false }}\n&& true\n'
        # runs as '&& true' is added as string ("false\n&& true\n")
        # equiv: format('{0}\n&& true\n', false)
        if: |
          ${{
            false
          }}
          && true
        run: echo "it runs"

      - name: 'true\n&& {{ false }}\n&& true\n'
        # the block is still a string
        # equiv: format('true\n&& {0}\n&& true\n', false)
        if: |
          true
          && ${{
            false
          }}
          && true
        run: echo "it runs"

      - name: 'true && {{ false }}\n&& true\n'
        # equiv: format('true && {0}\n&& true\n', false)
        if: |
          true && ${{ false }}
          && true
        run: echo "it runs"

      - name: 'true && {{ false }}\n&& true'
        # equiv: format('true && {0}\n&& true', false)
        if: |-
          true && ${{ false }}
          && true
        run: echo "it runs"

      - name: 'true && {{ false }} && true'
        # equiv: format('true && {0} && true', false)
        if: true && ${{ false }} && true
        run: echo "it runs"

      - name: '{{ false }} == true'
        # equiv: format('{0} == true', false)
        if: ${{ false }} == true
        run: echo "it runs"

      - name: 'true && false && true'
        # equiv: true && false && true
        if: |
          true
          
          && false
          
          && true
        run: echo "it runs"
      
      - name: "'true'"
        # equiv: true
        if: 'true'
        run: echo "it runs"
      
      - name: "'false'"
        # equiv: false
        if: 'false'
        run: echo "it runs"
      
      - name: "{{ 'false' }}"
        # equiv: false
        if: ${{ 'false' }}
        run: echo "it runs"
      
      - name: "' false'"
        # equiv: false
        if: ' false'
        run: echo "it runs"
      
      - name: "' {{ false }}'"
        # equiv: format(' {0}, false)
        if: ' ${{ false }}'
        run: echo "it runs"
     
      - name: "' {{ false }} '"
        # equiv: format(' {0} ', false)
        if: ' ${{ false }} '
        run: echo "it runs"
      
      - name: "{{ 'fal' }}{{ 'se' }}"
        # equiv: format('{0}{1}', 'fal', 'se')
        # I actually thought this one would evaluate to false. /shrug
        if: ${{ 'fal' }}${{ 'se' }}
        run: echo "it runs"

      - name: "format('{0}', false)"
        # equiv: string 'false'
        if: format('{0}', false)
        run: echo "it runs"
      
      - name: "{{ format('{0}', false)"
        # equiv: string 'false'
        if: ${{ format('{0}', false) }}
        run: echo "it runs"
      
      - name: "env.forced_string_false"
        # equiv: string 'false'
        if: env.forced_string_false
        run: echo "it runs"
      
      - name: "{{ env.forced_string_false }}"
        # equiv: string 'false'
        if: ${{ env.forced_string_false }}
        run: echo "it runs"
      
      - name: "env.literal_string_false"
        # equiv: string 'false'
        if: env.literal_string_false
        run: echo "it runs"
      
      - name: "{{ env.literal_string_false }}"
        # equiv: string 'false'
        if: ${{ env.literal_string_false }}
        run: echo "it runs"
      
      - name: "env.actual_false"
        # equiv: string 'false'
        if: env.actual_false
        run: echo "it runs"
      
      - name: "{{ env.actual_false }}"
        # env is string
        if: ${{ env.actual_false }}
        run: echo "it runs"
      
      - name: "{{ false }}{{ '' }}"
        # equiv: string 'false'
        if: ${{ false }}${{ '' }}
        run: echo "it runs"
      
      - name: "{{ '' }}{{ '' }}"
        # equiv: ''
        # Falsy!
        if: ${{ '' }}${{ '' }}
        run: echo "it runs"
      
      - name: "{{ 0 }}{{ '' }}"
        # equiv: string '0'
        if: ${{ 0 }}${{ '' }}
        run: echo "it runs"
      
      - name: "{{ 0 }}{{ 0 }}"
        # equiv: '00'
        if: ${{ 0 }}${{ 0 }}
        run: echo "it runs"
      
      - name: "{{ false }}{{ false }}"
        # equiv: 'falsefalse'
        if: ${{ false }}${{ false }}
        run: echo "it runs"
      
      - name: "{{ false }}{{ null }}"
        # equiv: string 'false'
        if: ${{ false }}${{ null }}
        run: echo "it runs"
      
      - name: "{{ null }}{{ null }}"
        # equiv: empty string ''
        # Falsy!
        if: ${{ null }}${{ null }}
        run: echo "it runs"
      
      - name: "{{ 0 }}{{ null }}"
        # equiv: string '0'
        if: ${{ 0 }}${{ null }}
        run: echo "it runs"
      
      - name: "{{ NaN }}{{ NaN }}"
        # equiv: string 'NaNNaN'
        if: ${{ NaN }}${{ NaN }}
        run: echo "it runs"

      - name: show Join is better than concatonating {{ '' }}{{ '' }}
        # equiv: string ''
        # falsy!
        if: join(fromJSON('[null, null, "", "", null]'), '')
        run: echo "it runs"
      
      - name: "{{ '' }}{{ null }}{{ null }}{{ '' }}{{ '' }}"
        # equiv: ''
        # falsy!
        if: ${{ '' }}${{ null }}${{ null }}${{ '' }}${{ '' }}
        run: echo "it runs"
      
      - name: 'github.repository == "antdking/actions-scratch-pad"'
        if: github.repository == "antdking/actions-scratch-pad"
        run: echo "it runs"
      
      - name: "github.repository == 'antdking/actions-scratch-pad'"
        if: github.repository == 'antdking/actions-scratch-pad'
        run: echo "it runs"

      - name: '{{ github.repository }} == "antdking/actions-scratch-pad"'
        if: ${{ github.repository }} == "antdking/actions-scratch-pad"
        run: echo "it runs"
      
      - name: "{{ github.repository }} == 'antdking/actions-scratch-pad'"
        if: ${{ github.repository }} == 'antdking/actions-scratch-pad'
        run: echo "it runs"

      - name: "{{ github.repository == 'antdking/actions-scratch-pad' }}"
        if: ${{ github.repository == 'antdking/actions-scratch-pad' }}
        run: echo "it runs"
      
      - name: 'github.repository != "antdking/actions-scratch-pad"'
        if: github.repository != "antdking/actions-scratch-pad"
        run: echo "it runs"
      
      - name: "github.repository != 'antdking/actions-scratch-pad'"
        if: github.repository != 'antdking/actions-scratch-pad'
        run: echo "it runs"

      - name: '{{ github.repository }} != "antdking/actions-scratch-pad"'
        if: ${{ github.repository }} != "antdking/actions-scratch-pad"
        run: echo "it runs"
      
      - name: "{{ github.repository }} != 'antdking/actions-scratch-pad'"
        if: ${{ github.repository }} != 'antdking/actions-scratch-pad'
        run: echo "it runs"

      - name: "{{ github.repository != 'antdking/actions-scratch-pad'"
        if: ${{ github.repository != 'antdking/actions-scratch-pad' }}
        run: echo "it runs"

  stringFalse:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        stringFalse:
          - 'false'
          - ${{ 'false' }}
          - ${{ 'fa' }}${{ 'lse' }}
    steps:
      - name: messing with string falses
        if: matrix.stringFalse
        run: echo "it runs"
      - name: messing with string falses Wrapped
        if: ${{ matrix.stringFalse }}
        run: echo "it runs"
        

  testingSomething:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Jeff
        if: ' ${{ false }}'
        run: echo "it runs"
      - name: Jeff
        id: jeff
        if: ' ${{ false }}'
        run: echo "it runs"

  main:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "main SHOULD_RUN=${{ matrix.shouldRun }}"
    strategy:
      fail-fast: false
      matrix:
        shouldRun: [1, 0]
    env:
      SHOULD_RUN: ${{ matrix.shouldRun }}
    steps:
      - id: WRAPPED_LITERAL_CHOMP_CLIP
        name: WRAPPED_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LITERAL_CHOMP_STRIP
        name: WRAPPED_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LITERAL_CHOMP_KEEP
        name: WRAPPED_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_CLIP
        name: WRAPPED_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_STRIP
        name: WRAPPED_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_FOLDED_CHOMP_KEEP
        name: WRAPPED_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
      - id: WRAPPED_LEADING_LITERAL_CHOMP_CLIP
        name: WRAPPED_LEADING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_LITERAL_CHOMP_STRIP
        name: WRAPPED_LEADING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_LITERAL_CHOMP_KEEP
        name: WRAPPED_LEADING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_CLIP
        name: WRAPPED_LEADING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_STRIP
        name: WRAPPED_LEADING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_LEADING_FOLDED_CHOMP_KEEP
        name: WRAPPED_LEADING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}

      - id: WRAPPED_DANGLING_LITERAL_CHOMP_CLIP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_LITERAL_CHOMP_STRIP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_LITERAL_CHOMP_KEEP
        name: WRAPPED_DANGLING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_CLIP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_STRIP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_DANGLING_FOLDED_CHOMP_KEEP
        name: WRAPPED_DANGLING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_CLIP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_STRIP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_KEEP
        name: WRAPPED_LEADING_DANGLING_LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_CLIP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_STRIP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_KEEP
        name: WRAPPED_LEADING_DANGLING_FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          
          ${{
            always()
            && matrix.shouldRun == 1
          }}
          
      - id: LITERAL_CHOMP_CLIP
        name: LITERAL_CHOMP_CLIP
        run: echo "I Ran!"
        if: |
          always()
          && matrix.shouldRun == 1
          
      - id: LITERAL_CHOMP_STRIP
        name: LITERAL_CHOMP_STRIP
        run: echo "I Ran!"
        if: |-
          always()
          && matrix.shouldRun == 1
          
      - id: LITERAL_CHOMP_KEEP
        name: LITERAL_CHOMP_KEEP
        run: echo "I Ran!"
        if: |+
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_CLIP
        name: FOLDED_CHOMP_CLIP
        run: echo "I Ran!"
        if: >
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_STRIP
        name: FOLDED_CHOMP_STRIP
        run: echo "I Ran!"
        if: >-
          always()
          && matrix.shouldRun == 1
          
      - id: FOLDED_CHOMP_KEEP
        name: FOLDED_CHOMP_KEEP
        run: echo "I Ran!"
        if: >+
          always()
          && matrix.shouldRun == 1
          

      # validation
      - name: fail if any skipped when they should run
        if: |
          always()
          && matrix.shouldRun == 1
          && contains(steps.*.outcome, 'skipped')
        run: exit 1

      - name: fail if any ran while when they should not run
        if: |
          always()
          && matrix.shouldRun == 0
          && (
            contains(steps.*.outcome, 'success')
            || contains(steps.*.outcome, 'failure')
          )
        run: exit 1

      - name: dump results
        if: always()
        env:
          _STEPS_CONTEXT: ${{ toJSON(steps) }}
          _JOB_CONTEXT: ${{ toJSON(job) }}
          _STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          _MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          _STEP_ENV_CONTEXT: ${{ toJSON(env) }}
        run: |
          echo "steps: ${_STEPS_CONTEXT}"
          echo "job: ${_JOB_CONTEXT}"
          echo "strategy: ${_STRATEGY_CONTEXT}"
          echo "matrix: ${_MATRIX_CONTEXT}"
          echo "job env: ${_ENV_CONTEXT}"
          echo "step env: ${_STEP_ENV_CONTEXT}"
